stages:
  - install
  - build
  - build_docker
  - deploy

install_dependencies:
  stage: install
  image: node:23-alpine
  when: manual
  before_script:
    - corepack enable
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --frozen-lockfile --prefer-offline
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

build:
  stage: build
  image: node:23-alpine
  when: manual
  needs: ["install_dependencies"]
  before_script:
    - corepack enable
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

docker_build:
  stage: build_docker
  image: docker:latest
  variables:
    BACKEND_URL: "https://back.dev.skni.umcs.pl"
  services:
    - docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_COMMIT_BRANCH" .
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_COMMIT_BRANCH" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_COMMIT_BRANCH"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master
    - ci-test


deploy:
  stage: deploy
  trigger:
    project: "czujniki/infra"
    branch: "main"
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    FRONTEND_IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-$CI_COMMIT_BRANCH"
  only:
    - main
    - master